name: update profile README.md

on:
  schedule: # run automatically every 24 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # allows to manually run the job at any time
  push: # run on every push on the master branch
    branches:
      - main

jobs:
  update-readme:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true # [default: false] enable experimental features

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          # These entries are separated by newlines and have the form
          # `$workspace -> $target`. The `$target` part is treated as a directory
          # relative to the `$workspace` and defaults to "target" if not explicitly given.
          # default: ". -> target"
          workspaces: "processing/compile-typst"
      
      - name: Compile custom typst
        run: mise run compile:builder

      - name: Update README.md
        run: mise run rebuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}

      - run: git status

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: main
          commit_message: 'ci: update README.md'
          commit_options: '--all'
          file_pattern: 'dist/'